DROP DATABASE IF EXISTS databasekaraoke;
CREATE DATABASE databasekaraoke;
USE databasekaraoke;

DROP TABLE IF EXISTS CANCION_ARTISTA;
DROP TABLE IF EXISTS ARTISTA_AGRUPACION;
DROP TABLE IF EXISTS AGRUPACION;
DROP TABLE IF EXISTS ARTISTA;
DROP TABLE IF EXISTS CANCION;
DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS GENERO;

-- Notacion SQL
-- CREATE TABLE AGRUPACION (
--    "IDAGRUPACION" INTEGER PRIMARY KEY ,
--    NOMBREAGRUPACION TEXT NOT NULL
-- );

 -- Notacion MySQL

CREATE TABLE AGRUPACION (
    IDAGRUPACION INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREAGRUPACION VARCHAR(100) NOT NULL
);
CREATE TABLE GENERO (
    IDGENERO INT AUTO_INCREMENT PRIMARY KEY,
    TIPOGENERO VARCHAR(100) NOT NULL
);

CREATE TABLE ALBUM (
    IDALBUM INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREALBUM VARCHAR(100) NOT NULL,
    AÑOALBUM INTEGER
);

CREATE TABLE CANCION (
    IDCANCION INT AUTO_INCREMENT PRIMARY KEY,
    IDALBUM INT NOT NULL,
    IDGENERO INT NOT NULL,
    NOMBRECANCION VARCHAR(100) NOT NULL,
    LETRACANCION TEXT NOT NULL,
    FOREIGN KEY (IDALBUM) REFERENCES ALBUM(IDALBUM),
    FOREIGN KEY (IDGENERO) REFERENCES GENERO(IDGENERO)
);

CREATE TABLE ARTISTA (
    IDARTISTA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBREARTISTA VARCHAR(100) NOT NULL,
    PAISARTISTA VARCHAR(100) NOT NULL,
    BIOGRAFIAARTISTA TEXT,
    TIPOARTISTA VARCHAR(100) NOT NULL
);

CREATE TABLE CANCION_ARTISTA (
    IDCANCION INT,
    IDARTISTA INT,
    PRIMARY KEY (IDCANCION, IDARTISTA),
    FOREIGN KEY (IDCANCION) REFERENCES CANCION(IDCANCION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA)
);

CREATE TABLE ARTISTA_AGRUPACION (
    IDARTISTA INT,
    IDAGRUPACION INT,
    PRIMARY KEY (IDARTISTA,IDAGRUPACION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA),
    FOREIGN KEY (IDAGRUPACION) REFERENCES AGRUPACION(IDAGRUPACION)
);

-- BUSQUEDAS SIMPLES

-- Lista las canciones cuyos álbumes fueron lanzados un año específico.
SELECT
    c.NOMBRECANCION,
    al.AÑOALBUM
    FROM CANCION c JOIN ALBUM al
    ON c.IDALBUM = al.IDALBUM
    WHERE al.AÑOALBUM = 2023;

-- Listar todas las agrupaciones a las que pertenece cada artista.
SELECT
    A.NOMBREARTISTA,
    G.NOMBREAGRUPACION
    FROM ARTISTA A JOIN ARTISTA_AGRUPACION AG
       ON A.IDARTISTA = AG.IDARTISTA
       JOIN AGRUPACION G ON AG.IDAGRUPACION = G.IDAGRUPACION
       ORDER BY A.NOMBREARTISTA;

-- Buscar todas las canciones cuyo nombre empiece con s
SELECT
    c.NOMBRECANCION
FROM CANCION c
WHERE c.NOMBRECANCION LIKE 's%';

-- Buscar todas las canciones de shakira con su genero y album
SELECT
    C.NOMBRECANCION,
    G.TIPOGENERO,
    AL.NOMBREALBUM
FROM CANCION C JOIN GENERO G ON C.IDGENERO = G.IDGENERO
JOIN ALBUM  AL ON C.IDALBUM = AL.IDALBUM
JOIN CANCION_ARTISTA CA on C.IDCANCION = CA.IDCANCION
JOIN ARTISTA A on CA.IDARTISTA = A.IDARTISTA
WHERE A.NOMBREARTISTA LIKE '%Residente%';

-- BUSCA CANCIONES DE REGUETON
SELECT
    C.NOMBRECANCION,
    G.TIPOGENERO
    FROM CANCION C JOIN GENERO G ON C.IDGENERO = G.IDGENERO
    WHERE G.TIPOGENERO = 'Regueton';

-- CANCIONES DE RIHANNA
SELECT
    A.NOMBREARTISTA,
    A.PAISARTISTA,
    C.NOMBRECANCION
FROM ARTISTA A JOIN CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
JOIN CANCION C on CA.IDCANCION = C.IDCANCION
WHERE NOMBREARTISTA = 'Rihanna';

-- Obtener todos los álbumes creados entre LOS años (por ejemplo 2000 y 2010).
SELECT
    AL.AÑOALBUM,
    AL.NOMBREALBUM
FROM ALBUM AL
WHERE AL.AÑOALBUM BETWEEN 2000 AND 2010
ORDER BY AÑOALBUM;

-- BUSQUEDAS AVANZADAS
-- Obtén los artistas que han pertenecido a más de una agrupación.
SELECT
    a.NOMBREARTISTA,
    COUNT(DISTINCT ag.NOMBREAGRUPACION) AS "Numero de AGRUPACIONES"
FROM ARTISTA a
JOIN ARTISTA_AGRUPACION a_a ON a.IDARTISTA = a_a.IDARTISTA
JOIN AGRUPACION ag ON ag.IDAGRUPACION = a_a.IDAGRUPACION
GROUP BY a.NOMBREARTISTA
HAVING COUNT(DISTINCT ag.NOMBREAGRUPACION) > 1;

-- Listar artistas con su nacionalidad y el número total de canciones que han grabado.
SELECT
    A.NOMBREARTISTA,
    COUNT(DISTINCT C.IDCANCION) AS CantidadCanciones
FROM ARTISTA A
JOIN CANCION_ARTISTA CA ON A.IDARTISTA = CA.IDARTISTA
JOIN CANCION C ON CA.IDCANCION = C.IDCANCION
GROUP BY A.IDARTISTA, A.NOMBREARTISTA, A.PAISARTISTA
ORDER BY A.PAISARTISTA;

-- Cantidad de artistas en cada agrupación (bandas)
SELECT
    AG.NOMBREAGRUPACION,
    COUNT(DISTINCT A.IDARTISTA)
FROM ARTISTA A JOIN ARTISTA_AGRUPACION AA on A.IDARTISTA = AA.IDARTISTA
JOIN AGRUPACION AG on AA.IDAGRUPACION = AG.IDAGRUPACION
GROUP BY AG.NOMBREAGRUPACION;

-- Géneros con más de 2 canciones almacenadas
SELECT
    G.TIPOGENERO,
    COUNT(DISTINCT C.IDCANCION) AS CANTIDADCANCIONES
    FROM CANCION C JOIN GENERO G on C.IDGENERO = G.IDGENERO
    GROUP BY G.TIPOGENERO;


-- Contar cuántos álbumes existen por año
SELECT
    A.AÑOALBUM,
    COUNT(DISTINCT A.NOMBREALBUM)
    FROM ALBUM A
    GROUP BY A.AÑOALBUM
    ORDER BY AÑOALBUM;

-- Obtén los artistas que han cantado canciones de 2 o más géneros distintos, mostrando:
SELECT
    A.NOMBREARTISTA,
    COUNT(DISTINCT  C.IDGENERO) AS NumeroGeneros
    FROM ARTISTA A JOIN CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
    JOIN CANCION C on CA.IDCANCION = C.IDCANCION
    JOIN  GENERO G on C.IDGENERO = G.IDGENERO
    GROUP BY A.NOMBREARTISTA
    HAVING NumeroGeneros >= 2
    ORDER BY NumeroGeneros DESC;


-- Genera un listado de artistas ordenado del más productivo al menos productivo,
SELECT
    A.NOMBREARTISTA,
    COUNT(DISTINCT C.IDCANCION) AS Productividad
    FROM ARTISTA A JOIN  CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
    JOIN CANCION C on CA.IDCANCION = C.IDCANCION
    GROUP BY NOMBREARTISTA
    ORDER BY Productividad DESC;


# Vista_1 Canciones con artista, álbum y género

CREATE VIEW vw_canciones_detalle AS
SELECT
    c.IDCANCION,
    c.NOMBRECANCION,
    al.NOMBREALBUM,
    al.AÑOALBUM,
    g.TIPOGENERO,
    a.NOMBREARTISTA
FROM CANCION c
JOIN ALBUM al ON c.IDALBUM = al.IDALBUM
JOIN GENERO g ON c.IDGENERO = g.IDGENERO
JOIN CANCION_ARTISTA ca ON c.IDCANCION = ca.IDCANCION
JOIN ARTISTA a ON ca.IDARTISTA = a.IDARTISTA
ORDER BY a.IDARTISTA;
SELECT * FROM vw_canciones_detalle;

# Vista_2 Artistas con número total de canciones

CREATE VIEW vw_artistas_cantidad_canciones AS
SELECT
    a.IDARTISTA,
    a.NOMBREARTISTA,
    COUNT(ca.IDCANCION) AS TOTAL_CANCIONES
FROM ARTISTA a
LEFT JOIN CANCION_ARTISTA ca ON a.IDARTISTA = ca.IDARTISTA
GROUP BY a.IDARTISTA, a.NOMBREARTISTA;

SELECT * FROM vw_artistas_cantidad_canciones;

# Vista_3 Agrupaciones con número de integrantes

CREATE VIEW vw_agrupaciones_integrantes AS
SELECT
    ag.NOMBREAGRUPACION,
    COUNT(aa.IDARTISTA) AS TOTAL_INTEGRANTES
FROM AGRUPACION ag
JOIN ARTISTA_AGRUPACION aa ON ag.IDAGRUPACION = aa.IDAGRUPACION
GROUP BY ag.NOMBREAGRUPACION;

SELECT * FROM vw_agrupaciones_integrantes;

# Funcion_1 Cantidad de canciones de un artista

DELIMITER $$

CREATE FUNCTION fn_canciones_por_artista(p_id_artista INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE total INT;
    SELECT COUNT(*) INTO total
    FROM CANCION_ARTISTA
    WHERE IDARTISTA = p_id_artista;
    RETURN total;
END$$

DELIMITER ;

SELECT fn_canciones_por_artista(1) AS Canciones_Adele;

# Función_2 Cantidad de agrupaciones de un artista

DELIMITER $$

CREATE FUNCTION fn_agrupaciones_por_artista(p_id_artista INT)
RETURNS INT
DETERMINISTIC
BEGIN
    DECLARE total INT;
    SELECT COUNT(*) INTO total
    FROM ARTISTA_AGRUPACION
    WHERE IDARTISTA = p_id_artista;
    RETURN total;
END$$

DELIMITER ;

SELECT fn_agrupaciones_por_artista(47) AS Agrupaciones_Shakira;

# Funcion_3 (Tabular) Canciones por género

DELIMITER $$

CREATE FUNCTION fn_canciones_por_genero(p_genero VARCHAR(100))
RETURNS TABLE (
    NombreCancion VARCHAR(100),
    Album VARCHAR(100),
    Artista VARCHAR(100);
)
DROP PROCEDURE IF EXISTS sp_canciones_por_genero;
DELIMITER $$

CREATE PROCEDURE sp_canciones_por_genero(IN p_genero VARCHAR(100))
BEGIN
    SELECT
        c.NOMBRECANCION,
        al.NOMBREALBUM,
        a.NOMBREARTISTA
    FROM CANCION c
    JOIN ALBUM al ON c.IDALBUM = al.IDALBUM
    JOIN GENERO g ON c.IDGENERO = g.IDGENERO
    JOIN CANCION_ARTISTA ca ON c.IDCANCION = ca.IDCANCION
    JOIN ARTISTA a ON ca.IDARTISTA = a.IDARTISTA
    WHERE g.TIPOGENERO = p_genero;
END$$

DELIMITER ;


CALL sp_canciones_por_genero('Pop');

# Procedimientos_1 Agregación + Parámetros --- cambiar

DELIMITER $$

CREATE PROCEDURE sp_resumen_artista(IN p_id_artista INT)
BEGIN
    SELECT
        a.NOMBREARTISTA,
        COUNT(ca.IDCANCION) AS TotalCanciones
    FROM ARTISTA a
    JOIN CANCION_ARTISTA ca ON a.IDARTISTA = ca.IDARTISTA
    WHERE a.IDARTISTA = p_id_artista
    GROUP BY a.NOMBREARTISTA;
END$$

DELIMITER ;

CALL sp_resumen_artista(1);

# Procedimiento_2 Canciones por año

DELIMITER $$

CREATE PROCEDURE sp_canciones_por_anio(IN p_anio INT)
BEGIN
    SELECT
        c.NOMBRECANCION,
        al.AÑOALBUM
    FROM CANCION c
    JOIN ALBUM al ON c.IDALBUM = al.IDALBUM
    WHERE al.AÑOALBUM = p_anio;
END$$

DELIMITER ;

CALL sp_canciones_por_anio(2023);

# procedimiento_3 listado de artistas por país

DELIMITER $$

CREATE PROCEDURE sp_artistas_por_pais(IN p_pais VARCHAR(100))
BEGIN
    SELECT
        NOMBREARTISTA,
        TIPOARTISTA
    FROM ARTISTA
    WHERE PAISARTISTA = p_pais;
END$$

DELIMITER ;

CALL sp_artistas_por_pais('Estados Unidos');

# TRiggers_1 Tabla de auditoría

CREATE TABLE AUDITORIA_CANCION (
    IDAUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    ACCION VARCHAR(50),
    IDCANCION INT,
    FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

#TRiggers1 After Insert

DELIMITER $$

CREATE TRIGGER trg_insert_cancion
AFTER INSERT ON CANCION
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CANCION (ACCION, IDCANCION)
    VALUES ('INSERT', NEW.IDCANCION);
END$$

DELIMITER ;

#TRiggers_2 After Delete

DELIMITER $$

CREATE TRIGGER trg_delete_cancion
AFTER DELETE ON CANCION
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_CANCION (ACCION, IDCANCION)
    VALUES ('DELETE', OLD.IDCANCION);
END$$

DELIMITER ;

# TRigger_3 Before Insert (validacion)
DELIMITER $$

CREATE TRIGGER trg_validar_letra
BEFORE INSERT ON CANCION
FOR EACH ROW
BEGIN
    IF NEW.LETRACANCION IS NULL OR NEW.LETRACANCION = '' THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'La letra de la canción no puede estar vacía';
    END IF;
END$$

DELIMITER ;

