DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CANCION;
DROP TABLE IF EXISTS AGRUPACION;
DROP TABLE IF EXISTS CANCION_ARTISTA;
DROP TABLE IF EXISTS ARTISTA;
DROP TABLE IF EXISTS ARTISTA_AGRUPACION;

CREATE TABLE AGRUPACION (
    "IDAGRUPACION" INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREAGRUPACION TEXT NOT NULL
);

CREATE TABLE GENERO (
    IDGENERO INTEGER PRIMARY KEY AUTOINCREMENT,
    TIPOGENERO TEXT NOT NULL
);

CREATE TABLE ALBUM (
    IDALBUM INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREALBUM TEXT NOT NULL,
    AÑOALBUM INTEGER
);

CREATE TABLE CANCION (
    IDCANCION INTEGER PRIMARY KEY AUTOINCREMENT,
    IDALBUM INTEGER NOT NULL,
    IDGENERO INTEGER NOT NULL,
    NOMBRECANCION TEXT NOT NULL,
    LETRACANCION TEXT NOT NULL,
    FOREIGN KEY (IDALBUM) REFERENCES ALBUM(IDALBUM),
    FOREIGN KEY (IDGENERO) REFERENCES GENERO(IDGENERO)
);

CREATE TABLE ARTISTA (
    IDARTISTA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREARTISTA TEXT NOT NULL,
    PAISARTISTA TEXT NOT NULL,
    BIOGRAFIAARTISTA TEXT,
    TIPOARTISTA TEXT NOT NULL
);

CREATE TABLE CANCION_ARTISTA (
    IDCANCION INTEGER,
    IDARTISTA INTEGER,
    PRIMARY KEY (IDCANCION, IDARTISTA),
    FOREIGN KEY (IDCANCION) REFERENCES CANCION(IDCANCION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA)
);

CREATE TABLE ARTISTA_AGRUPACION (
    IDARTISTA INTEGER,
    IDAGRUPACION INTEGER,
    PRIMARY KEY (IDARTISTA,IDAGRUPACION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA),
    FOREIGN KEY (IDAGRUPACION) REFERENCES AGRUPACION(IDAGRUPACION)
);

--BUSQUEDAS SIMPLES

--Busqueda de Aritstas por pais especifico
SELECT
    a.NOMBREARTISTA,
    a.TIPOARTISTA
    FROM ARTISTA a
    WHERE a.PAISARTISTA = 'España';

--Lista las canciones cuyos álbumes fueron lanzados un año específico.
SELECT
    c.NOMBRECANCION,
    al.AÑOALBUM
    FROM CANCION c JOIN ALBUM al
    ON c.IDALBUM = al.IDALBUM
    WHERE al.AÑOALBUM = 2023;

--Listar todas las agrupaciones a las que pertenece cada artista.
SELECT
    A.NOMBREARTISTA,
    G.NOMBREAGRUPACION
    FROM ARTISTA A JOIN ARTISTA_AGRUPACION AG
       ON A.IDARTISTA = AG.IDARTISTA
       JOIN AGRUPACION G ON AG.IDAGRUPACION = G.IDAGRUPACION
       ORDER BY A.NOMBREARTISTA;
--Buscar todas las canciones cuyo nombre empiece con s
SELECT
    c.NOMBRECANCION
FROM CANCION c
WHERE c.NOMBRECANCION LIKE 's%';

--Buscar todas las canciones de shakira con su genero y album
SELECT
    C.NOMBRECANCION,
    G.TIPOGENERO,
    AL.NOMBREALBUM
FROM CANCION C JOIN GENERO G ON C.IDGENERO = G.IDGENERO
JOIN ALBUM  AL ON C.IDALBUM = AL.IDALBUM
JOIN CANCION_ARTISTA CA on C.IDCANCION = CA.IDCANCION
JOIN ARTISTA A on CA.IDARTISTA = A.IDARTISTA
WHERE A.NOMBREARTISTA LIKE '%Shakira%';
--BUSCA CANCIONES DE REGUETON
SELECT
    C.NOMBRECANCION,
    G.TIPOGENERO
    FROM CANCION C JOIN GENERO G ON C.IDGENERO = G.IDGENERO
    WHERE G.TIPOGENERO = "Regueton";
---CANCIONES DE RIHANNA
SELECT
    A.NOMBREARTISTA,
    A.PAISARTISTA,
    C.NOMBRECANCION
FROM ARTISTA A JOIN CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
JOIN CANCION C on CA.IDCANCION = C.IDCANCION
WHERE NOMBREARTISTA = 'Rihanna';

--Obtener todos los álbumes creados entre LOS años (por ejemplo 2000 y 2010).
SELECT
    AL.AÑOALBUM,
    AL.NOMBREALBUM
FROM ALBUM AL
WHERE AL.AÑOALBUM BETWEEN 2000 AND 2010
ORDER BY AÑOALBUM;

--BUSQUEDAS AVANZADAS
--Los álbumes y muestra junto a cada uno el país del artista principal que participa en sus canciones.
SELECT
    al.NOMBREALBUM,
    a.PAISARTISTA
 FROM ALBUM al JOIN CANCION c
    ON  al.IDALBUM = c.IDALBUM
    JOIN CANCION_ARTISTA CA on c.IDCANCION = CA.IDCANCION
    JOIN ARTISTA A on CA.IDARTISTA = A.IDARTISTA
    GROUP BY NOMBREALBUM;

--Obtén los artistas que han pertenecido a más de una agrupación.
SELECT
    a.NOMBREARTISTA,
    COUNT(DISTINCT ag.NOMBREAGRUPACION) AS "Numero de AGRUPACIONES"
FROM ARTISTA a
JOIN ARTISTA_AGRUPACION a_a ON a.IDARTISTA = a_a.IDARTISTA
JOIN AGRUPACION ag ON ag.IDAGRUPACION = a_a.IDAGRUPACION
GROUP BY a.NOMBREARTISTA
HAVING COUNT(DISTINCT ag.NOMBREAGRUPACION) > 1;

--Listar artistas con su nacionalidad y el número total de canciones que han grabado.
SELECT
    A.NOMBREARTISTA,
    A.PAISARTISTA,
    COUNT(DISTINCT C.IDCANCION) AS CantidadCanciones
FROM ARTISTA A
JOIN CANCION_ARTISTA CA ON A.IDARTISTA = CA.IDARTISTA
JOIN CANCION C ON CA.IDCANCION = C.IDCANCION
GROUP BY A.IDARTISTA, A.NOMBREARTISTA, A.PAISARTISTA
ORDER BY A.PAISARTISTA;

--Cantidad de artistas en cada agrupación (bandas)
SELECT
    AG.NOMBREAGRUPACION,
    COUNT(DISTINCT A.IDARTISTA)
FROM ARTISTA A JOIN ARTISTA_AGRUPACION AA on A.IDARTISTA = AA.IDARTISTA
JOIN AGRUPACION AG on AA.IDAGRUPACION = AG.IDAGRUPACION
GROUP BY AG.NOMBREAGRUPACION;

--Géneros con más de 2 canciones almacenadas
SELECT
    G.TIPOGENERO,
    COUNT(DISTINCT C.IDCANCION) AS CANTIDADCANCIONES
    FROM CANCION C JOIN GENERO G on C.IDGENERO = G.IDGENERO
    GROUP BY G.TIPOGENERO
    HAVING CANTIDADCANCIONES > 2;

--Contar cuántos álbumes existen por año
SELECT
    A.AÑOALBUM,
    COUNT (DISTINCT A.NOMBREALBUM)
    FROM ALBUM A
    GROUP BY A.AÑOALBUM
    ORDER BY AÑOALBUM;

--Obtén los artistas que han cantado canciones de 2 o más géneros distintos, mostrando:
SELECT
    A.NOMBREARTISTA,
    COUNT(DISTINCT  C.IDGENERO) AS NumeroGeneros
    FROM ARTISTA A JOIN CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
    JOIN CANCION C on CA.IDCANCION = C.IDCANCION
    JOIN  GENERO G on C.IDGENERO = G.IDGENERO
    GROUP BY A.NOMBREARTISTA
    HAVING NumeroGeneros >= 2
    ORDER BY NumeroGeneros DESC;


--Genera un listado de artistas ordenado del más productivo al menos productivo,
SELECT
    A.NOMBREARTISTA,
    COUNT(DISTINCT C.IDCANCION) AS Productividad
    FROM ARTISTA A JOIN  CANCION_ARTISTA CA on A.IDARTISTA = CA.IDARTISTA
    JOIN CANCION C on CA.IDCANCION = C.IDCANCION
    GROUP BY NOMBREARTISTA
    ORDER BY Productividad DESC;