DROP TABLE IF EXISTS ALBUM;
DROP TABLE IF EXISTS GENERO;
DROP TABLE IF EXISTS CANCION;
DROP TABLE IF EXISTS AGRUPACION;
DROP TABLE IF EXISTS CANCION_ARTISTA;
DROP TABLE IF EXISTS ARTISTA;
DROP TABLE IF EXISTS ARTISTA_AGRUPACION;

CREATE TABLE AGRUPACION (
    "IDAGRUPACION" INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREAGRUPACION TEXT NOT NULL
);

CREATE TABLE GENERO (
    IDGENERO INTEGER PRIMARY KEY AUTOINCREMENT,
    TIPOGENERO TEXT NOT NULL
);

CREATE TABLE ALBUM (
    IDALBUM INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREALBUM TEXT NOT NULL,
    AÑOALBUM INTEGER
);

CREATE TABLE CANCION (
    IDCANCION INTEGER PRIMARY KEY AUTOINCREMENT,
    IDALBUM INTEGER NOT NULL,
    IDGENERO INTEGER NOT NULL,
    NOMBRECANCION TEXT NOT NULL,
    LETRACANCION TEXT NOT NULL,
    FOREIGN KEY (IDALBUM) REFERENCES ALBUM(IDALBUM),
    FOREIGN KEY (IDGENERO) REFERENCES GENERO(IDGENERO)
);

CREATE TABLE ARTISTA (
    IDARTISTA INTEGER PRIMARY KEY AUTOINCREMENT,
    NOMBREARTISTA TEXT NOT NULL,
    PAISARTISTA TEXT NOT NULL,
    BIOGRAFIAARTISTA TEXT,
    TIPOARTISTA TEXT NOT NULL
);

CREATE TABLE CANCION_ARTISTA (
    IDCANCION INTEGER,
    IDARTISTA INTEGER,
    PRIMARY KEY (IDCANCION, IDARTISTA),
    FOREIGN KEY (IDCANCION) REFERENCES CANCION(IDCANCION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA)
);

CREATE TABLE ARTISTA_AGRUPACION (
    IDARTISTA INTEGER,
    IDAGRUPACION INTEGER,
    PRIMARY KEY (IDARTISTA,IDAGRUPACION),
    FOREIGN KEY (IDARTISTA) REFERENCES ARTISTA(IDARTISTA),
    FOREIGN KEY (IDAGRUPACION) REFERENCES AGRUPACION(IDAGRUPACION)
);

SELECT *
FROM GENERO;

SELECT
    a.IDARTISTA,
    ag.NOMBREAGRUPACION,
    a.NOMBREARTISTA,
    a.PAISARTISTA,
    a.BIOGRAFIAARTISTA,
    a.TIPOARTISTA
FROM ARTISTA a
JOIN AGRUPACION ag
    ON a.IDAGRUPACION = ag.IDAGRUPACION
WHERE ag.NOMBREAGRUPACION = 'SODA ESTEREO';


