
--INSERTAR GENEROS
INSERT INTO GENERO (TIPOGENERO) VALUES ('Pop');        --1
INSERT INTO GENERO (TIPOGENERO) VALUES ('Rock');       --2
INSERT INTO GENERO (TIPOGENERO) VALUES ('Reguetón');   --3
INSERT INTO GENERO (TIPOGENERO) VALUES ('Rap');        --4
INSERT INTO GENERO (TIPOGENERO) VALUES ('Jazz');       --5
INSERT INTO GENERO (TIPOGENERO) VALUES ('Electrónica');--6
INSERT INTO GENERO (TIPOGENERO) VALUES ('Blues');      --7
INSERT INTO GENERO (TIPOGENERO) VALUES ('Salsa');      --8
INSERT INTO GENERO (TIPOGENERO) VALUES ('Metal');      --9
INSERT INTO GENERO (TIPOGENERO) VALUES ('Country');    --10
INSERT INTO GENERO (TIPOGENERO) VALUES ('Folk');       --11
INSERT INTO GENERO (TIPOGENERO) VALUES ('Clásica');    --12


--ADELE
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Adele', 'Reino Unido', 'Cantante y compositora', 'Vocalista'); --adele

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('21', 2011); --adele

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (1, 1, 'Rolling in the Deep', 'We could have had it all...'); --adele

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (1, 1); --adele


--ARIANAGRANDE
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Ariana Grande', 'Estados Unidos', 'Cantante y actriz', 'Vocalista'); --arianagrande

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Thank U, Next', 2019); --arianagrande

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (2, 1, '7 Rings', 'I want it, I got it...'); --arianagrande

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (2, 2); --arianagrande


--TAYLORSWIFT
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Taylor Swift', 'Estados Unidos', 'Cantante y compositora', 'Vocalista'); --taylorswift

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('1989', 2014); --taylorswift

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (3, 1, 'Blank Space', 'Got a long list of ex-lovers...'); --taylorswift

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (3, 3); --taylorswift


--ROSALIA
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Rosalía', 'España', 'Cantante y compositora', 'Vocalista'); --rosalia

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Motomami', 2022); --rosalia

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (4, 3, 'Saoko', 'Saoko papi saoko...'); --rosalia

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (4, 4); --rosalia


--SABRINACARPENTER
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Sabrina Carpenter', 'Estados Unidos', 'Cantante y actriz', 'Vocalista'); --sabrinacarpenter

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Emails I Can’t Send', 2022); --sabrinacarpenter

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (5, 1, 'Nonsense', 'This song is nonsense...'); --sabrinacarpenter

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (5, 5); --sabrinacarpenter

--MILEYCYRUS
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Miley Cyrus', 'Estados Unidos', 'Cantante y actriz', 'Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Endless Summer Vacation', 2023);

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (6, 1, 'Flowers', 'I can buy myself flowers...');

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (6, 6);


--BRUNOMARS
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Bruno Mars', 'Estados Unidos', 'Cantante, compositor y productor', 'Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('24K Magic', 2016);

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (7, 1, '24K Magic', 'Players, put yo pinky rings up...');

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (7, 7);


--EDSHEERAN
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Ed Sheeran', 'Reino Unido', 'Cantante y compositor', 'Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Divide', 2017);

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (8, 1, 'Shape of You', 'Im in love with the shape of you...');

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (8, 8);


--RIHANNA
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Rihanna', 'Barbados', 'Cantante y empresaria', 'Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('Anti', 2016);

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (9, 1, 'Work', 'Work work work...');

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (9, 9);


--DAVIDBOWIE
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('David Bowie', 'Reino Unido', 'Cantante y compositor', 'Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM)
VALUES ('The Rise and Fall of Ziggy Stardust', 1972);

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (10, 2, 'Starman', 'There’s a starman waiting in the sky...');

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA)
VALUES (10, 10);

--SODAESTEREO
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Soda Estereo');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Gustavo Cerati', 'Argentina', 'Vocalista Soda Estereo', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Zeta Bosio', 'Argentina', 'Bajista Soda Estereo', 'Bajista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Charly Alberti', 'Argentina', 'Baterista Soda Estereo', 'Baterista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (11, 1);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (12, 1);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (13, 1);

--ÁLBUM Y CANCIONES
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Doble Vida', 1988);  -- IDALBUM = 11

INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (11, 2, 'Ciudad de la furia', 'Me verás volver...');  -- IDCANCION = 11

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (11, 11);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (11, 12);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (11, 13);

--2. Hombres G
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Hombres G');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('David Summers', 'España', 'Vocalista y bajista', 'Vocalista-Bajista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Rafael Gutiérrez', 'España', 'Guitarrista', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Daniel Mezquita', 'España', 'Guitarrista rítmico', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Javier Molina', 'España', 'Baterista', 'Baterista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (14, 2);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (15, 2);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (16, 2);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (17, 2);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Hombres G', 1985);  -- IDALBUM = 12
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (12, 2, 'Devuélveme a mi chica', 'Sufro por ti...');  -- IDCANCION = 12

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12, 14);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12, 15);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12, 16);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12, 17);

--3. Miranda
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Miranda');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Ale Sergi', 'Argentina', 'Vocalista', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Bruno de Vincenti', 'Argentina', 'Tecladista', 'Tecladista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (18, 3);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (19, 3);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Sin Restricciones', 2004);  -- IDALBUM = 13
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (13, 1, 'Don', 'La chica de ayer...');  -- IDCANCION = 13

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (13, 18);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (13, 19);

--4. The Police
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The Police');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Sting', 'Reino Unido', 'Vocalista y bajista', 'Vocalista-Bajista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Andy Summers', 'Reino Unido', 'Guitarrista', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Stewart Copeland', 'Reino Unido', 'Baterista', 'Baterista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (20, 4);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (21, 4);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (22, 4);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Synchronicity', 1983);  -- IDALBUM = 14
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (14, 1, 'Every Breath You Take', 'Every move you make...');  -- IDCANCION = 14

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (14, 20);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (14, 21);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (14, 22);
--5. Héroes del Silencio
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Héroes del Silencio');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Enrique Bunbury', 'España', 'Vocalista', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Juan Valdivia', 'España', 'Guitarrista', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Joaquín Cardiel', 'España', 'Bajista', 'Bajista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Pedro Andreu', 'España', 'Baterista', 'Baterista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (26, 5);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (27, 5);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (28, 5);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (29, 5);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Senderos de Traición', 1990); -- IDALBUM = 17
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (17, 9, 'Entre Dos Tierras', 'Vuelvo a ti...'); -- IDCANCION = 15

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15, 26);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15, 27);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15, 28);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15, 29);

--6. Mecano
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Mecano');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Ana Torroja', 'España', 'Vocalista', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('José María Cano', 'España', 'Compositor y tecladista', 'Tecladista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Nacho Cano', 'España', 'Compositor y guitarrista', 'Guitarrista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (30, 6);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (31, 6);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (32, 6);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Entre el cielo y el suelo', 1986); -- IDALBUM = 18
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (18, 7, 'Hijo de la Luna', 'Luna, luna...'); -- IDCANCION = 16

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (16, 30);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (16, 31);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (16, 32);

--7. Bacilos
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Bacilos');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Jorge Villamizar', 'Colombia', 'Vocalista y guitarra', 'Vocalista-Guitarra');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Andrés Castro', 'Colombia', 'Guitarrista y coros', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('José Javier Freire', 'Puerto Rico', 'Bajista', 'Bajista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (33, 7);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (34, 7);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (35, 7);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Bacilos', 2000); -- IDALBUM = 19
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (19, 1, 'Caraluna', 'Caraluna...'); -- IDCANCION = 17

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (17, 33);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (17, 34);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (17, 35);

--8. Zoé
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Zoé');

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Leon Larregui', 'México', 'Vocalista', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Sergio Acosta', 'México', 'Guitarrista', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Jesus Báez', 'México', 'Baterista', 'Baterista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (36, 8);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (37, 8);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (38, 8);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Memo Rex Commander y el Corazón Atómico de la Vía Láctea', 2006); -- IDALBUM = 20
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (20, 11, 'Vía Láctea', 'Vía Láctea...'); -- IDCANCION = 18

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (18, 36);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (18, 37);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (18, 38);

--9. Aventura
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Aventura'); -- IDAGRUPACION = 9

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Romeo Santos', 'Estados Unidos', 'Vocalista y compositor', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Lenny Santos', 'Estados Unidos', 'Guitarrista', 'Guitarrista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Henry Santos', 'Estados Unidos', 'Corista', 'Corista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Max Santos', 'Estados Unidos', 'Bajista', 'Bajista');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (39, 9);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (40, 9);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (41, 9);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (42, 9);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('We Broke the Rules', 2002); -- IDALBUM = 21
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (21, 8, 'Obsesión', 'Cada vez que te veo...'); -- IDCANCION = 19

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19, 39);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19, 40);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19, 41);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19, 42);

--10. Calle 13
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Calle 13'); -- IDAGRUPACION = 10

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Residente', 'Puerto Rico', 'Vocalista principal', 'Vocalista');
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Visitante', 'Puerto Rico', 'Productor y DJ', 'Productor-DJ');

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (43, 10);
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (44, 10);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Residente o Visitante', 2007); -- IDALBUM = 22
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (22, 3, 'Atrévete-te-te', 'Atrévete-te-te...'); -- IDCANCION = 20

INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (20, 43);
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (20, 44);

--DUETOS

INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA) VALUES ('Lady Gaga', 'Estados Unidos', 'Cantante y actriz', 'Vocalista'); -- Lady Gaga
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA) VALUES ('Alejandro Sanz', 'España', 'Cantante y compositor', 'Vocalista'); -- Alejandro Sanz
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA) VALUES ('Bizarrap', 'Argentina', 'Productor musical', 'Productor'); -- Bizarrap
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA) VALUES ('Mon Laferte', 'Chile', 'Cantante y compositora', 'Vocalista'); -- Mon Laferte
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA) VALUES ('Mark Ronson', 'Reino Unido', 'Productor y músico', 'Productor'); -- Mark Ronson

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Shakira-Rihanna'); -- IDAGRUPACION = 46
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Shakira-Gustavo Cerati'); -- IDAGRUPACION = 47
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Taylor Swift-Sabrina Carpenter'); -- IDAGRUPACION = 48
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Karol G-Shakira'); -- IDAGRUPACION = 49
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Bruno Mars-Mark Ronson'); -- IDAGRUPACION = 50
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('David Bowie-Queen'); -- IDAGRUPACION = 51
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Shakira-Alejandro Sanz'); -- IDAGRUPACION = 52
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Residente-Bizarrap'); -- IDAGRUPACION = 53
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Bunbury-Mon Laferte'); -- IDAGRUPACION = 54
INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Bruno Mars-Lady Gaga'); -- IDAGRUPACION = 55

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (8,46); -- Shakira-Rihanna: Shakira
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (9,46); -- Shakira-Rihanna: Rihanna

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (8,47); -- Shakira-Cerati: Shakira
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (4,47); -- Shakira-Cerati: Cerati

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (3,48); -- Taylor-Sabrina: Taylor Swift
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (5,48); -- Taylor-Sabrina: Sabrina Carpenter

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (10,49); -- Karol G-Shakira: Karol G
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (8,49); -- Karol G-Shakira: Shakira

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (7,50); -- Bruno Mars-Mark Ronson: Bruno Mars
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (49,50); -- Bruno Mars-Mark Ronson: Mark Ronson

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (12,51); -- David Bowie-Queen: David Bowie
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (11,51); -- David Bowie-Queen: Queen (miembro relevante)

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (8,52); -- Shakira-Alejandro Sanz: Shakira
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (46,52); -- Shakira-Alejandro Sanz: Alejandro Sanz

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (43,53); -- Residente-Bizarrap: Residente
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (47,53); -- Residente-Bizarrap: Bizarrap

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (13,54); -- Bunbury-Mon Laferte: Bunbury
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (48,54); -- Bunbury-Mon Laferte: Mon Laferte

INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (7,55); -- Bruno Mars-Lady Gaga: Bruno Mars
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (45,55); -- Bruno Mars-Lady Gaga: Lady Gaga

--Shakira-Rihanna
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Beautiful Liar', 2007); -- IDALBUM = 20
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (20,1,'Beautiful Liar','Tell me why am I not enough alone...'); -- IDCANCION = 11
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (11,8); -- Shakira
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (11,9); -- Rihanna

--Shakira-Cerati
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('No', 2008); -- IDALBUM = 21
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (21,2,'No','No quiero verte sufrir...'); -- IDCANCION = 12
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12,8); -- Shakira
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (12,4); -- Cerati

--Taylor Swift-Sabrina Carpenter
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Bad Reputation', 2022); -- IDALBUM = 22
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (22,1,'Bad Reputation','We don’t care what they say...'); -- IDCANCION = 13
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (13,3); -- Taylor Swift
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (13,5); -- Sabrina Carpenter

--Karol G-Shakira
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('TQG', 2023); -- IDALBUM = 23
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (23,3,'TQG','Te quiero grande...'); -- IDCANCION = 14
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (14,10); -- Karol G
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (14,8); -- Shakira

--Bruno Mars-Mark Ronson
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Uptown Funk', 2014); -- IDALBUM = 24
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (24,6,'Uptown Funk','This hit, that ice cold...'); -- IDCANCION = 15
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15,7); -- Bruno Mars
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (15,49); -- Mark Ronson

--David Bowie-Queen
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Under Pressure', 1981); -- IDALBUM = 25
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (25,9,'Under Pressure','Pressure pushing down on me...'); -- IDCANCION = 16
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (16,12); -- David Bowie
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (16,11); -- Queen (miembro relevante)

--Shakira-Alejandro Sanz
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('La Tortura', 2005); -- IDALBUM = 26
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (26,3,'La Tortura','Ay papi, yo sé que tú me amas...'); -- IDCANCION = 17
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (17,8); -- Shakira
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (17,46); -- Alejandro Sanz

--Residente-Bizarrap
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('BZRP Music Sessions #49', 2022); -- IDALBUM = 27
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (27,4,'BZRP Music Sessions #49','Lírica intensa y ritmo urbano...'); -- IDCANCION = 18
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (18,43); -- Residente
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (18,47); -- Bizarrap

--Bunbury-Mon Laferte
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Amor Ausente', 2023); -- IDALBUM = 28
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (28,4,'Amor Ausente','Entre la distancia y el deseo...'); -- IDCANCION = 19
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19,13); -- Bunbury
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (19,48); -- Mon Laferte

--Bruno Mars-Lady Gaga
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Die with a Smile', 2020); -- IDALBUM = 29
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (29,1,'Die with a smile','If the world was ending'); -- IDCANCION = 20
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (20,7); -- Bruno Mars
INSERT INTO CANCION_ARTISTA (IDCANCION, IDARTISTA) VALUES (20,45); -- Lady Gaga


--1. Paul McCartney en The Beatles y Wings
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Paul McCartney','Reino Unido','Bajista y compositor de The Beatles y Wings','Vocalista-Bajista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Wings'); -- IDAGRUPACION 56
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (49,56); -- Paul McCartney

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Band on the Run',1973); -- IDALBUM 30
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (30,10,'Band on the Run','Jet wait to...'); -- IDCANCION 21
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (21,49);

--2. Michael Jackson (solista)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Michael Jackson','Estados Unidos','Rey del Pop','Vocalista');

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Thriller',1982); -- IDALBUM 31
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (31,1,'Billie Jean','She was more like a beauty queen...'); -- IDCANCION 22
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (22,50);

--3. Julian Casablancas en The Strokes y The Voidz
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Julian Casablancas','Estados Unidos','Vocalista de The Strokes y The Voidz','Vocalista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The Strokes'); -- IDAGRUPACION 57
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (51,57);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Is This It',2001); -- IDALBUM 32
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (32,2,'Last Nite','Last night, she said...'); -- IDCANCION 23
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (23,51);

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The Voidz'); -- IDAGRUPACION 58
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (51,58);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Virtue',2018); -- IDALBUM 33
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (33,1,'Leave It In My Dreams','Lyrics of Voidz...'); -- IDCANCION 24
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (24,51);

--4. Dave Grohl (Foo Fighters y Nirvana) ya agregado, solo ejemplo de otra canción en Foo Fighters
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Wasting Light',2011); -- IDALBUM 34
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (34,9,'Rope','Pick it up, pick it up...'); -- IDCANCION 25
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (25,9);

--5. Sting (The Police y solista)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Sting','Reino Unido','Vocalista y bajista de The Police','Vocalista-Bajista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The Police'); -- IDAGRUPACION 59
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (52,59);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Synchronicity',1983); -- IDALBUM 35
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (35,6,'Every Breath You Take','Every breath you take...'); -- IDCANCION 26
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (26,52);

--6. Jack White (The White Stripes y The Raconteurs)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Jack White','Estados Unidos','Guitarrista y vocalista de White Stripes y Raconteurs','Vocalista-Guitarrista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The White Stripes'); -- IDAGRUPACION 60
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (53,60);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Elephant',2003); -- IDALBUM 36
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (36,2,'Seven Nation Army','Im gonna fight them off...'); -- IDCANCION 27
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (27,53);

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('The Raconteurs'); -- IDAGRUPACION 61
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (53,61);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Consolers of the Lonely',2008); -- IDALBUM 37
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (37,11,'Salute Your Solution','Lyrics...'); -- IDCANCION 28
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (28,53);

--7. Beyoncé (Destiny's Child y solista)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Beyoncé','Estados Unidos','Vocalista de Destiny''s Child y solista','Vocalista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Destiny''s Child'); -- IDAGRUPACION 62
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (54,62);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Survivor',2001); -- IDALBUM 38
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (38,1,'Survivor','I am a survivor...'); -- IDCANCION 29
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (29,54);

--8. Freddie Mercury (Queen y solista) ya agregado, hacemos canción solista
INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Mr. Bad Guy',1985); -- IDALBUM 39
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (39,1,'Living on My Own','Lyrics...'); -- IDCANCION 30
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (30,2);

--9. Josh Homme (Queens of the Stone Age y Them Crooked Vultures)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Josh Homme','Estados Unidos','Vocalista y guitarrista de QOTSA y TCV','Vocalista-Guitarrista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Queens of the Stone Age'); -- IDAGRUPACION 63
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (55,63);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Songs for the Deaf',2002); -- IDALBUM 40
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (40,11,'No One Knows','Lyrics...'); -- IDCANCION 31
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (31,55);

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Them Crooked Vultures'); -- IDAGRUPACION 64
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (55,64);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Them Crooked Vultures',2009); -- IDALBUM 41
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (41,2,'New Fang','Lyrics...'); -- IDCANCION 32
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (32,55);

--10. Jack Bruce (Cream y West, Bruce & Laing)
INSERT INTO ARTISTA (NOMBREARTISTA, PAISARTISTA, BIOGRAFIAARTISTA, TIPOARTISTA)
VALUES ('Jack Bruce','Reino Unido','Bajista y vocalista de Cream y West, Bruce & Laing','Vocalista-Bajista');

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('Cream'); -- IDAGRUPACION 65
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (56,65);

INSERT INTO ALBUM (NOMBREALBUM, AÑOALBUM) VALUES ('Disraeli Gears',1967); -- IDALBUM 42
INSERT INTO CANCION (IDALBUM, IDGENERO, NOMBRECANCION, LETRACANCION)
VALUES (42,5,'Sunshine of Your Love','Lyrics...'); -- IDCANCION 33
INSERT INTO CANCION_ARTISTA(IDCANCION, IDARTISTA) VALUES (33,56);

INSERT INTO AGRUPACION (NOMBREAGRUPACION) VALUES ('West, Bruce & Laing'); -- IDAGRUPACION 66
INSERT INTO ARTISTA_AGRUPACION (IDARTISTA, IDAGRUPACION) VALUES (56,66);
